### ISSUE TITLE
function of `invert_sigmoid` is not in the paper 

### ISSUE THREAD

**Issue by tarepan** [ben-hayes/sinusoidal-gradient-descent#1]
## Summary
Current implementation use `invert_sigmoid` flag in multi-oscillator experiments.  
It change initial α<sub>k</sub> from *1/|K|* to *log(1/(|K|-1))*.  
The paper state that they are initialized with *1/|K|*, but it is not matched with actual implementation.  
What is the porpose and function of this processing?

## Current State
The implementation has `invert_sigmoid` flag in initializer.  
https://github.com/ben-hayes/sinusoidal-gradient-descent/blob/191c98d4068b83181a24eb970f98ca75834f9c66/sinusoidal_gradient_descent/eval/estimator.py#L234-L236

And it is activated in 'multi' experiments.  
https://github.com/ben-hayes/sinusoidal-gradient-descent/blob/191c98d4068b83181a24eb970f98ca75834f9c66/estimator_config/param_sampler/multi.yaml#L11

However, the paper stated that  
> linear amplitude was initialized for each component at ^α_k = 1/|K|.

so there seems to be an unmatch between implementation and paper.

## Question
I have two questions.  

- What is the function and purpose of *invert_sigmoid*?  
- Which way is used for the paper's results?  

## Others
The paper was so impressive for me.  
With this method, I successfully analyze/synthesize a human voice and it has very high naturality.  
Thanks for your great work!

**Comment by ben-hayes** [comment]
Hi @tarepan 

Thanks for raising the issue and for your keen eye! We have `invert_sigmoid` because we apply a sigmoid function to the amplitude before multiplying it with the frequency component to ensure that it is bounded in `[0, 1]`.

Setting `invert_sigmoid=True` simply ensures that the actual amplitude (i.e. the linear factor of the frequency component) is uniformly initialised in the interval `[0, 1/|K|]` rather than `[sigmoid(0), sigmoid(1/|K|)]`. 

Thanks for pointing this out though — you made me realise this is not clear at all in the paper, so I will upload a revision to arXiv shortly.

Glad to hear that you've been having success with this method anyway :)

**Comment by tarepan** [comment]
Thanks for your quick response!  
I understand, so write down memo for somebody who have same question in future.  

## Purpose
The purpose is ensuring amplitude α<sub>k</sub> bounded in `[0, 1]`, and keep it differentiable.  

## Approach
We apply sigmoid toward `global_amp`.  
https://github.com/ben-hayes/sinusoidal-gradient-descent/blob/191c98d4068b83181a24eb970f98ca75834f9c66/sinusoidal_gradient_descent/eval/estimator.py#L317-L320

With sigmoid, we can compress `global_amp` range from `[-inf, +inf]` to `[0, 1]`, and keep meaningful gradient.  

This processing means that `global_amp` is not equal to α<sub>k</sub>, it is rather a 'inverse_sigmoid(α<sub>k</sub>)'.  
`global_amp` is inversed, so `sigmoid(global_amp)` == 'sigmoid(inverse_sigmoid(α<sub>k</sub>))' == 'α<sub>k</sub>'.  

## Initialization trick
We hope to initialize α<sub>k</sub> with 1/|K|.  
`global_amp` is 'inverse_sigmoid(α<sub>k</sub>)', so we initialize `global_amp` with 'inverse_sigmoid(1/|K|)'.  
https://github.com/ben-hayes/sinusoidal-gradient-descent/blob/191c98d4068b83181a24eb970f98ca75834f9c66/sinusoidal_gradient_descent/eval/estimator.py#L232-L236
`log(x/(1-x))` is called *logit* function, and it is the inverse function of sigmoid.  
`invert_sigmoid` is flag for this processing.  

## Others
Glad to contribute to good paper's revision. I am looking forward to new version!
