### ISSUE TITLE
Non-overriden Hydra config

### ISSUE THREAD

**Issue by tarepan** [ben-hayes/sinusoidal-gradient-descent#4]
## Summary
When run experiments with `evaluate_estimator`, the parameters are wrong.  
It is caused by wrong settings of hydra config.  
I will make PR to fix it.  
Is this bug affects results in the paper?  

## Bug
Check configs with `evaluate_estimator -cn multi_fft_2 --cfg job` (dry run flag for config).  
It is |K| == 2 setup, but hydra says it is ***4***.  

```yaml
param_sampler:
  n_sinusoids: 4
  ...
dataset:
  n_components: 4
  ...
```

When I check Tensor shape with debug codes, it seems to be K==4.  
I got same results in fft_8 and fft_32.  

## Cause
Wrong setting of config cause this bug.  

Hydra recommend `_self_` at ***end*** of defaults list.  
> As of Hydra 1.1, config.yaml is overriding configs from the Defaults List
> ...
> If the new behavior works for your application, append _self_ to the ***end*** of the Defaults List.
> https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order/

Current implementation place `_self_` at ***head***.  
https://github.com/ben-hayes/sinusoidal-gradient-descent/blob/191c98d4068b83181a24eb970f98ca75834f9c66/estimator_config/multi_fft_2.yaml#L1-L3

This cause non-overriden configs (default |K| is 4 for multi experiments).  

## Fix
When I place `_self_` at end, |K| become properly ***2***.  

## PR
If this is a bug (not intented results), I am willing to make the PR.  
Is this a bug?  

## Paper's results
Are there any impact on the results of the paper?  
If this code is used as it is for the paper, |K| related results could have some problem.

**Comment by ben-hayes** [comment]
Hi @tarepan, great catch! 

This does appear to be a bug, but does not impact the results of the paper, as multi_fft_* experiments for the paper were launched with the following shell script:

```bash
CUDA_VISIBLE_DEVICES=$1 evaluate_estimator \
    -cn=multi\
    device=cuda\
    n_steps=250000\
    batch_size=2048\
    optimizer.lr=1e-4\
    param_sampler.n_sinusoids=2\
    dataset.n_components=2\
    dataset.n_samples=2000\
    dataset.n_snrs=1\
    +dataset.enable_noise=false\
    evaluation.normalise_complex_grads=false\
    loss=fft_loss\
    amplitude_estimator=fft\
    +param_sampler.all_random_in_batch=true\
    seeds="[1234]"\
    output_file=results/multi_sinusoid_fft_long_2.csv

CUDA_VISIBLE_DEVICES=$1 evaluate_estimator \
    -cn=multi\
    device=cuda\
    n_steps=250000\
    batch_size=2048\
    optimizer.lr=1e-4\
    param_sampler.n_sinusoids=8\
    dataset.n_components=8\
    dataset.n_samples=2000\
    dataset.n_snrs=1\
    +dataset.enable_noise=false\
    evaluation.normalise_complex_grads=false\
    loss=fft_loss\
    amplitude_estimator=fft\
    +param_sampler.all_random_in_batch=true\
    seeds="[2345]"\
    output_file=results/multi_sinusoid_fft_long_8.csv

CUDA_VISIBLE_DEVICES=$1 evaluate_estimator \
    -cn=multi\
    device=cuda\
    n_steps=250000\
    batch_size=2048\
    optimizer.lr=1e-4\
    param_sampler.n_sinusoids=32\
    dataset.n_components=32\
    dataset.n_samples=2000\
    dataset.n_snrs=1\
    +dataset.enable_noise=false\
    evaluation.normalise_complex_grads=false\
    loss=fft_loss\
    amplitude_estimator=fft\
    +param_sampler.all_random_in_batch=true\
    seeds="[3456]"\
    output_file=results/multi_sinusoid_fft_long_32.csv
```

These individual Hydra configs were simply to capture these parameters for reproducibility, and placing _self_ first is just a typo!

Thanks very much for flagging this though — a PR would be very welcome!

**Comment by tarepan** [comment]
Thanks for quick response, no problem in the paper is good news!  
I made a PR for future users (#5).
